export {
  isAdmin,
  isHr,
  isAdminOrHr,
  isManagerRole,
  canApproveLeave,
  canManageAllLeaves,
  canViewAllSalaries,
  canManageEmployees,
  canManagePolicies,
  canManageHolidays,
  canEditLeaveBalance,
  canApplyLeaveOnBehalf,
  canUploadPayslip,
  canAccessCompanySettings,
  canAccessDepartments,
  canAccessReports,
  isManager,
} from "@/lib/permissions";
